name: Call PR bump
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

permissions:
  contents: write

jobs:
  call-bump:
    uses: juv-dev/workflows-frontend/.github/workflows/create-version.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
