name: Delete Branch After Merge

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, edited]

jobs:
  delete-merged-branch:
    if: github.event.pull_request.merged == true
    uses: juv-dev/workflows-frontend/.github/workflows/delete-branch-after-merge.yml@main
    with:
      branch_name: ${{ github.event.pull_request.head.ref }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}