# En delete-branch.yml
name: Delete Branch After Merge

on:
  workflow_run:
    workflows: ["Call Tag on merge"]  # Nombre exacto del workflow de tags
    types: [completed]

jobs:
  delete-branch:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ github.event.workflow_run.event.pull_request.head.ref }}